-- Rename database identifiers only. No row values are changed by this migration.
-- Prisma applies PostgreSQL migrations transactionally, so every DDL operation is atomic.

DO $$
DECLARE
  pair record;
BEGIN
  FOR pair IN
    SELECT * FROM (VALUES
      ('Role', 'UserRole'),
      ('EntidadPago', 'PaymentEntity'),
      ('TipoMedioPago', 'PaymentMethodType'),
      ('EstadoMedioPago', 'PaymentMethodStatus'),
      ('TipoCuentaFondos', 'FundsAccountType'),
      ('EstadoCuentaFondos', 'FundsAccountStatus'),
      ('TipoAcreedor', 'CreditorType'),
      ('EstadoAcreedor', 'CreditorStatus'),
      ('TipoDocumentoPago', 'PaymentDocumentType'),
      ('EstadoCircuitoFactura', 'InvoiceWorkflowStatus'),
      ('OrigenFacturaGestoria', 'AccountingInvoiceOrigin'),
      ('JustificanteGasto', 'ExpenseReceiptType'),
      ('EstadoGastoCorriente', 'CurrentExpenseStatus'),
      ('EstadoPago', 'PaymentStatus'),
      ('TipoAplicacionPago', 'PaymentApplicationType'),
      ('FuncionPago', 'PaymentFunction'),
      ('TipoMovimientoFondos', 'FundsMovementType'),
      ('DireccionMovimientoExtracto', 'StatementMovementDirection'),
      ('EstadoMovimientoExtracto', 'StatementMovementStatus'),
      ('EstadoArqueoCaja', 'CashCountStatus'),
      ('EstadoReposicionCaja', 'CashReplenishmentStatus'),
      ('EstadoCierreMensual', 'MonthlyCloseStatus')
    ) AS names(old_name, new_name)
  LOOP
    EXECUTE format('ALTER TYPE %I RENAME TO %I', pair.old_name, pair.new_name);
  END LOOP;
END $$;

DO $$
DECLARE
  pair record;
BEGIN
  FOR pair IN
    SELECT * FROM (VALUES
      ('Shift', 'turno', 'shift'),
      ('Shift', 'efectivo', 'cash'),
      ('Shift', 'caixa', 'caixaBankAmount'),
      ('Shift', 'santander', 'santanderAmount'),
      ('Shift', 'efectivoGasto', 'cashExpense'),
      ('Shift', 'fondoInicial', 'openingFund'),
      ('Shift', 'fondoFinal', 'closingFund'),
      ('Expense', 'proveedor', 'supplier'),
      ('Expense', 'importe', 'amount'),
      ('CierreTurno', 'numeroCierreCaja', 'cashCloseNumber'),
      ('CierreTurno', 'tpv', 'pos'),
      ('CierreTurno', 'fechaHoraApertura', 'openingDateTime'),
      ('CierreTurno', 'fechaHoraCierre', 'closingDateTime'),
      ('CierreTurno', 'fondoCajaAnterior', 'previousCashFund'),
      ('CierreTurno', 'cobrosEfectivo', 'cashReceipts'),
      ('CierreTurno', 'reembolsosEfectivo', 'cashRefunds'),
      ('CierreTurno', 'depositado', 'depositedAmount'),
      ('CierreTurno', 'pagosSalidas', 'paymentOutflows'),
      ('CierreTurno', 'efectivoTeoricoCaja', 'theoreticalCash'),
      ('CierreTurno', 'cantidadEfectivoReal', 'actualCash'),
      ('CierreTurno', 'descuadre', 'cashVariance'),
      ('CierreTurno', 'ventasBrutas', 'grossSales'),
      ('CierreTurno', 'reembolsos', 'refunds'),
      ('CierreTurno', 'descuentos', 'discounts'),
      ('CierreTurno', 'ventasNetas', 'netSales'),
      ('CierreTurno', 'ventasEfectivo', 'cashSales'),
      ('CierreTurno', 'ventasTarjeta', 'cardSales'),
      ('CierreTurno', 'ivaPan4Base', 'breadVat4Base'),
      ('CierreTurno', 'ivaPan4Cuota', 'breadVat4Amount'),
      ('CierreTurno', 'iva10Base', 'vat10Base'),
      ('CierreTurno', 'iva10Cuota', 'vat10Amount'),
      ('CierreTurno', 'observacionDescuadre', 'varianceNote'),
      ('CierreTurno', 'confirmadoPorId', 'confirmedById'),
      ('CierreTurno', 'confirmadoAt', 'confirmedAt'),
      ('Catalogo', 'tipo', 'type'),
      ('Catalogo', 'valor', 'value'),
      ('Catalogo', 'descripcion', 'description'),
      ('Catalogo', 'prefijoCodigo', 'codePrefix'),
      ('Catalogo', 'activo', 'active'),
      ('Proveedor', 'razonSocial', 'legalName'),
      ('Proveedor', 'cifNif', 'taxId'),
      ('Proveedor', 'direccionFiscal', 'billingAddress'),
      ('Proveedor', 'contactoNombre', 'contactName'),
      ('Proveedor', 'contactoTelefono', 'contactPhone'),
      ('Proveedor', 'contactoEmail', 'contactEmail'),
      ('Proveedor', 'categoriaServicio', 'serviceCategory'),
      ('Proveedor', 'condicionesPago', 'paymentTerms'),
      ('Proveedor', 'plazoEntregaDias', 'deliveryLeadTimeDays'),
      ('Proveedor', 'pedidoMinimo', 'minimumOrder'),
      ('Proveedor', 'notasCondiciones', 'termsNotes'),
      ('Proveedor', 'frecuenciaEntrega', 'deliveryFrequency'),
      ('Proveedor', 'horarioEntrega', 'deliverySchedule'),
      ('Proveedor', 'metodoPedido', 'orderingMethod'),
      ('Proveedor', 'fechaAlta', 'addedAt'),
      ('Proveedor', 'estado', 'status'),
      ('Proveedor', 'valoracionFiabilidad', 'reliabilityRating'),
      ('Proveedor', 'valoracionCalidad', 'qualityRating'),
      ('Proveedor', 'valoracionPrecio', 'priceRating'),
      ('Proveedor', 'incidencias', 'issues'),
      ('Proveedor', 'observaciones', 'notes'),
      ('ProveedorProducto', 'proveedorId', 'supplierId'),
      ('ProveedorProducto', 'productoId', 'productId'),
      ('ProveedorProducto', 'refProveedor', 'supplierReference'),
      ('ProveedorProducto', 'precioCompraSinIva', 'purchasePriceExcludingVat'),
      ('ProveedorProducto', 'plazoEntregaDias', 'deliveryLeadTimeDays'),
      ('ProveedorProducto', 'pedidoMinimo', 'minimumOrder'),
      ('ProveedorProducto', 'esPrincipal', 'isPrimary'),
      ('ProveedorProducto', 'activo', 'active'),
      ('Recepcion', 'codigoAlbaran', 'deliveryNoteCode'),
      ('Recepcion', 'proveedorId', 'supplierId'),
      ('Recepcion', 'facturaId', 'invoiceId'),
      ('Recepcion', 'fechaRecepcion', 'receivedAt'),
      ('Recepcion', 'notas', 'notes'),
      ('Factura', 'proveedorId', 'supplierId'),
      ('Factura', 'serie', 'series'),
      ('Factura', 'numero', 'number'),
      ('Factura', 'fechaExpedicion', 'issueDate'),
      ('Factura', 'fechaOperacion', 'operationDate'),
      ('Factura', 'fechaVencimiento', 'dueDate'),
      ('Factura', 'fechaPago', 'paymentDate'),
      ('Factura', 'numeroPedido', 'orderNumber'),
      ('Factura', 'fechaPedido', 'orderDate'),
      ('Factura', 'centroEntrega', 'deliveryCenter'),
      ('Factura', 'referenciaAlbaran', 'deliveryNoteReference'),
      ('Factura', 'fechaAlbaran', 'deliveryNoteDate'),
      ('Factura', 'formaPago', 'paymentMethod'),
      ('Factura', 'estado', 'status'),
      ('Factura', 'estadoPago', 'paymentStatus'),
      ('Factura', 'moneda', 'currency'),
      ('Factura', 'importePagado', 'paidAmount'),
      ('Factura', 'entidad', 'entity'),
      ('Factura', 'tipoDocumento', 'documentType'),
      ('Factura', 'estadoCircuito', 'workflowStatus'),
      ('Factura', 'acreedorId', 'creditorId'),
      ('Factura', 'importeConformado', 'confirmedAmount'),
      ('Factura', 'importeRetenido', 'withheldAmount'),
      ('Factura', 'motivoRetencion', 'withholdingReason'),
      ('Factura', 'referenciaOrigen', 'sourceReference'),
      ('Factura', 'esLegacyPago', 'isLegacyPayment'),
      ('Factura', 'razonSocialEmisor', 'issuerLegalName'),
      ('Factura', 'nifEmisor', 'issuerTaxId'),
      ('Factura', 'domicilioFiscalEmisor', 'issuerBillingAddress'),
      ('Factura', 'totalNeto', 'netTotal'),
      ('Factura', 'totalDescuento', 'discountTotal'),
      ('Factura', 'totalIva', 'totalVat'),
      ('Factura', 'totalRecargo', 'surchargeTotal'),
      ('Factura', 'totalRetenciones', 'withholdingTotal'),
      ('Factura', 'importeTotal', 'totalAmount'),
      ('Factura', 'observaciones', 'notes'),
      ('Factura', 'alertas', 'alerts'),
      ('Factura', 'confirmadoPorId', 'confirmedById'),
      ('Factura', 'confirmadoAt', 'confirmedAt'),
      ('FacturaLinea', 'facturaId', 'invoiceId'),
      ('FacturaLinea', 'productoId', 'productId'),
      ('FacturaLinea', 'tipoLinea', 'lineType'),
      ('FacturaLinea', 'referenciaProveedor', 'supplierReference'),
      ('FacturaLinea', 'codigoArticulo', 'itemCode'),
      ('FacturaLinea', 'descripcion', 'description'),
      ('FacturaLinea', 'unidadMedida', 'unitOfMeasure'),
      ('FacturaLinea', 'formatoOriginal', 'originalFormat'),
      ('FacturaLinea', 'cantidad', 'quantity'),
      ('FacturaLinea', 'descuentoPorcentaje', 'discountPercentage'),
      ('FacturaLinea', 'descuentoImporte', 'discountAmount'),
      ('FacturaLinea', 'precioUnitario', 'unitPrice'),
      ('FacturaLinea', 'precioUnitarioNeto', 'netUnitPrice'),
      ('FacturaLinea', 'baseImponible', 'taxableBase'),
      ('FacturaLinea', 'tipoIva', 'vatRate'),
      ('FacturaLinea', 'cuotaIva', 'vatAmount'),
      ('FacturaLinea', 'totalLinea', 'lineTotal'),
      ('FacturaLinea', 'lote', 'batch'),
      ('FacturaLinea', 'fechaVencimiento', 'dueDate'),
      ('FacturaLinea', 'alertaValidacion', 'validationAlert'),
      ('FacturaImpuesto', 'facturaId', 'invoiceId'),
      ('FacturaImpuesto', 'tipo', 'type'),
      ('FacturaImpuesto', 'porcentaje', 'percentage'),
      ('FacturaImpuesto', 'baseImponible', 'taxableBase'),
      ('FacturaImpuesto', 'cuota', 'taxAmount'),
      ('FacturaGestoria', 'fecha', 'date'),
      ('FacturaGestoria', 'facturaNumero', 'invoiceNumber'),
      ('FacturaGestoria', 'proveedorAcreedor', 'supplierOrCreditor'),
      ('FacturaGestoria', 'nif', 'taxId'),
      ('FacturaGestoria', 'concepto', 'concept'),
      ('FacturaGestoria', 'baseExenta', 'exemptBase'),
      ('FacturaGestoria', 'iva21', 'vat21'),
      ('FacturaGestoria', 'iva10', 'vat10'),
      ('FacturaGestoria', 'iva4', 'vat4'),
      ('FacturaGestoria', 'iva2', 'vat2'),
      ('FacturaGestoria', 'totalIva', 'totalVat'),
      ('FacturaGestoria', 'irpf', 'withholdingTax'),
      ('FacturaGestoria', 'totalFactura', 'invoiceTotal'),
      ('FacturaGestoria', 'formaPago', 'paymentMethod'),
      ('FacturaGestoria', 'textoOCR', 'ocrText'),
      ('FacturaGestoria', 'origen', 'source'),
      ('FacturaGestoria', 'alertas', 'alerts'),
      ('FacturaGestoria', 'creadoPorId', 'createdById'),
      ('RecepcionLinea', 'recepcionId', 'receiptId'),
      ('RecepcionLinea', 'productoId', 'productId'),
      ('RecepcionLinea', 'cantidadRecibida', 'receivedQuantity'),
      ('RecepcionLinea', 'precioUnitario', 'unitPrice'),
      ('RecepcionLinea', 'lote', 'batch'),
      ('RecepcionLinea', 'fechaVencimiento', 'dueDate'),
      ('InventarioFisico', 'fechaConteo', 'countedAt'),
      ('InventarioFisico', 'creadoById', 'createdById'),
      ('InventarioFisico', 'notas', 'notes'),
      ('InventarioFisicoLinea', 'inventarioFisicoId', 'physicalInventoryId'),
      ('InventarioFisicoLinea', 'productoId', 'productId'),
      ('InventarioFisicoLinea', 'cantidadUm1', 'quantityUnit1'),
      ('InventarioFisicoLinea', 'cantidadUm2', 'quantityUnit2'),
      ('Producto', 'codigo', 'code'),
      ('Producto', 'codBarrasEan', 'eanBarcode'),
      ('Producto', 'descripcionTpv', 'posDescription'),
      ('Producto', 'descripcionCompleta', 'fullDescription'),
      ('Producto', 'tipoArticulo', 'itemType'),
      ('Producto', 'familia', 'family'),
      ('Producto', 'subfamilia', 'subfamily'),
      ('Producto', 'seccion', 'section'),
      ('Producto', 'esComprable', 'isPurchasable'),
      ('Producto', 'esElaborado', 'isPrepared'),
      ('Producto', 'esVendible', 'isSellable'),
      ('Producto', 'llevaReceta', 'hasRecipe'),
      ('Producto', 'umBaseStock', 'baseStockUnit'),
      ('Producto', 'umCompra', 'purchaseUnit'),
      ('Producto', 'factorCompraABase', 'purchaseToBaseFactor'),
      ('Producto', 'umVenta', 'salesUnit'),
      ('Producto', 'factorVentaABase', 'salesToBaseFactor'),
      ('Producto', 'pesoNetoUdG', 'netWeightPerUnitGrams'),
      ('Producto', 'formatoPresentacion', 'presentationFormat'),
      ('Producto', 'costeUmBase', 'baseUnitCost'),
      ('Producto', 'costeConIva', 'costIncludingVat'),
      ('Producto', 'mermaEstandarPct', 'standardWastePercentage'),
      ('Producto', 'codIva', 'vatCode'),
      ('Producto', 'ivaPct', 'vatPercentage'),
      ('Producto', 'ivaCompraPct', 'purchaseVatPercentage'),
      ('Producto', 'ivaVentaPct', 'salesVatPercentage'),
      ('Producto', 'metodoPrecio', 'pricingMethod'),
      ('Producto', 'margenObjetivoPct', 'targetMarginPercentage'),
      ('Producto', 'pvpObjetivoConIva', 'targetRetailPriceIncludingVat'),
      ('Producto', 'pvpFijoConIva', 'fixedRetailPriceIncludingVat'),
      ('Producto', 'pvpAplicadoConIva', 'appliedRetailPriceIncludingVat'),
      ('Producto', 'pvpAplicadoSinIva', 'appliedRetailPriceExcludingVat'),
      ('Producto', 'gananciaEurUd', 'profitPerUnit'),
      ('Producto', 'margenRealPct', 'actualMarginPercentage'),
      ('Producto', 'desviacionPp', 'percentagePointDeviation'),
      ('Producto', 'diferenciaEurUd', 'unitDifference'),
      ('Producto', 'diagnosticoPrecio', 'pricingDiagnosis'),
      ('Producto', 'controlaStock', 'stockControl'),
      ('Producto', 'metodoValoracion', 'valuationMethod'),
      ('Producto', 'stockMinimo', 'minimumStock'),
      ('Producto', 'stockMaximo', 'maximumStock'),
      ('Producto', 'puntoPedido', 'reorderPoint'),
      ('Producto', 'ubicacion', 'location'),
      ('Producto', 'claseAbc', 'abcClass'),
      ('Producto', 'controlLote', 'batchControl'),
      ('Producto', 'vidaUtilDias', 'shelfLifeDays'),
      ('Producto', 'conservacion', 'storageConditions'),
      ('Producto', 'alergenos', 'allergens'),
      ('Producto', 'estado', 'status'),
      ('Producto', 'fechaAlta', 'addedAt'),
      ('Producto', 'observaciones', 'notes'),
      ('Producto', 'esEjemplo', 'isExample'),
      ('Acreedor', 'codigo', 'code'),
      ('Acreedor', 'tipo', 'type'),
      ('Acreedor', 'nombre', 'name'),
      ('Acreedor', 'nif', 'taxId'),
      ('Acreedor', 'entidadHabitual', 'defaultEntity'),
      ('Acreedor', 'cuentaDestinoUltimos4', 'destinationAccountLast4'),
      ('Acreedor', 'estado', 'status'),
      ('Acreedor', 'proveedorId', 'supplierId'),
      ('MedioPago', 'tipo', 'type'),
      ('MedioPago', 'requiereCuenta', 'requiresAccount'),
      ('MedioPago', 'conciliableBanco', 'bankReconciliable'),
      ('MedioPago', 'limiteOperacion', 'transactionLimit'),
      ('MedioPago', 'estado', 'status'),
      ('CuentaFondos', 'tipo', 'type'),
      ('CuentaFondos', 'entidad', 'entity'),
      ('CuentaFondos', 'descripcion', 'description'),
      ('CuentaFondos', 'ibanUltimos4', 'ibanLast4'),
      ('CuentaFondos', 'responsableId', 'responsibleUserId'),
      ('CuentaFondos', 'saldoTeorico', 'theoreticalBalance'),
      ('CuentaFondos', 'fondoFijo', 'fixedFloat'),
      ('CuentaFondos', 'estado', 'status'),
      ('CategoriaGasto', 'codigo', 'code'),
      ('CategoriaGasto', 'nombre', 'name'),
      ('CategoriaGasto', 'descripcion', 'description'),
      ('CategoriaGasto', 'activo', 'active'),
      ('ParametroAutorizacion', 'entidad', 'entity'),
      ('ParametroAutorizacion', 'codigo', 'code'),
      ('ParametroAutorizacion', 'valorDecimal', 'decimalValue'),
      ('ParametroAutorizacion', 'valorTexto', 'textValue'),
      ('ParametroAutorizacion', 'activo', 'active'),
      ('ParametroAutorizacion', 'vigenteDesde', 'validFrom'),
      ('ParametroAutorizacion', 'vigenteHasta', 'validTo'),
      ('ReglaAutorizacion', 'entidad', 'entity'),
      ('ReglaAutorizacion', 'importeDesde', 'amountFrom'),
      ('ReglaAutorizacion', 'importeHasta', 'amountTo'),
      ('ReglaAutorizacion', 'funcionRequerida', 'requiredFunction'),
      ('ReglaAutorizacion', 'activo', 'active'),
      ('ReglaAutorizacion', 'vigenteDesde', 'validFrom'),
      ('ReglaAutorizacion', 'vigenteHasta', 'validTo'),
      ('AsignacionPagoUsuario', 'entidad', 'entity'),
      ('AsignacionPagoUsuario', 'funcion', 'function'),
      ('AsignacionPagoUsuario', 'activo', 'active'),
      ('AsignacionPagoUsuario', 'vigenteDesde', 'validFrom'),
      ('AsignacionPagoUsuario', 'vigenteHasta', 'validTo'),
      ('ContratoRecurrente', 'entidad', 'entity'),
      ('ContratoRecurrente', 'acreedorId', 'creditorId'),
      ('ContratoRecurrente', 'categoriaId', 'categoryId'),
      ('ContratoRecurrente', 'concepto', 'concept'),
      ('ContratoRecurrente', 'importeEsperado', 'expectedAmount'),
      ('ContratoRecurrente', 'tolerancia', 'tolerance'),
      ('ContratoRecurrente', 'periodicidad', 'frequency'),
      ('ContratoRecurrente', 'fechaInicio', 'startDate'),
      ('ContratoRecurrente', 'fechaFin', 'endDate'),
      ('ContratoRecurrente', 'autorizadoPorId', 'authorizedById'),
      ('ContratoRecurrente', 'activo', 'active'),
      ('GastoCorriente', 'entidad', 'entity'),
      ('GastoCorriente', 'categoriaId', 'categoryId'),
      ('GastoCorriente', 'acreedorId', 'creditorId'),
      ('GastoCorriente', 'contratoId', 'contractId'),
      ('GastoCorriente', 'concepto', 'concept'),
      ('GastoCorriente', 'fechaDevengo', 'accrualDate'),
      ('GastoCorriente', 'importe', 'amount'),
      ('GastoCorriente', 'justificante', 'receipt'),
      ('GastoCorriente', 'solicitanteId', 'requesterId'),
      ('GastoCorriente', 'autorizadorId', 'authorizerId'),
      ('GastoCorriente', 'estado', 'status'),
      ('GastoCorriente', 'motivoRechazo', 'rejectionReason'),
      ('GastoCorriente', 'autorizadoAt', 'authorizedAt'),
      ('Anticipo', 'entidad', 'entity'),
      ('Anticipo', 'acreedorId', 'creditorId'),
      ('Anticipo', 'concepto', 'concept'),
      ('Anticipo', 'fecha', 'date'),
      ('Anticipo', 'importe', 'amount'),
      ('Anticipo', 'importeAplicado', 'appliedAmount'),
      ('Anticipo', 'solicitadoPorId', 'requestedById'),
      ('Anticipo', 'autorizadoPorId', 'authorizedById'),
      ('Anticipo', 'estado', 'status'),
      ('SecuenciaPago', 'entidad', 'entity'),
      ('SecuenciaPago', 'ultimoNumero', 'lastNumber'),
      ('Pago', 'numero', 'number'),
      ('Pago', 'entidad', 'entity'),
      ('Pago', 'fechaPago', 'paymentDate'),
      ('Pago', 'medioPagoId', 'paymentMethodId'),
      ('Pago', 'cuentaFondosId', 'fundsAccountId'),
      ('Pago', 'acreedorId', 'creditorId'),
      ('Pago', 'importeTotal', 'totalAmount'),
      ('Pago', 'referenciaExterna', 'externalReference'),
      ('Pago', 'ejecutadoPorId', 'executedById'),
      ('Pago', 'conciliado', 'reconciled'),
      ('Pago', 'estado', 'status'),
      ('Pago', 'excesoAutorizadoPorId', 'excessAuthorizedById'),
      ('Pago', 'motivoExceso', 'excessReason'),
      ('Pago', 'anuladoPorId', 'voidedById'),
      ('Pago', 'anuladoAt', 'voidedAt'),
      ('PagoAplicacion', 'pagoId', 'paymentId'),
      ('PagoAplicacion', 'tipoDestino', 'destinationType'),
      ('PagoAplicacion', 'facturaId', 'invoiceId'),
      ('PagoAplicacion', 'gastoId', 'currentExpenseId'),
      ('PagoAplicacion', 'anticipoId', 'advanceId'),
      ('PagoAplicacion', 'importeAplicado', 'appliedAmount'),
      ('AprobacionPago', 'pagoId', 'paymentId'),
      ('AprobacionPago', 'usuarioId', 'userId'),
      ('AprobacionPago', 'tipo', 'type'),
      ('AprobacionPago', 'motivo', 'reason'),
      ('MovimientoFondos', 'cuentaFondosId', 'fundsAccountId'),
      ('MovimientoFondos', 'entidad', 'entity'),
      ('MovimientoFondos', 'tipo', 'type'),
      ('MovimientoFondos', 'importe', 'amount'),
      ('MovimientoFondos', 'descripcion', 'description'),
      ('MovimientoFondos', 'origenTipo', 'sourceType'),
      ('MovimientoFondos', 'origenId', 'sourceId'),
      ('MovimientoFondos', 'pagoId', 'paymentId'),
      ('MovimientoFondos', 'creadoPorId', 'createdById'),
      ('ImportacionExtracto', 'cuentaFondosId', 'fundsAccountId'),
      ('ImportacionExtracto', 'nombreArchivo', 'fileName'),
      ('ImportacionExtracto', 'hashArchivo', 'fileHash'),
      ('ImportacionExtracto', 'fechaDesde', 'startDate'),
      ('ImportacionExtracto', 'fechaHasta', 'endDate'),
      ('ImportacionExtracto', 'creadaPorId', 'createdById'),
      ('MovimientoExtracto', 'importacionId', 'importId'),
      ('MovimientoExtracto', 'cuentaFondosId', 'fundsAccountId'),
      ('MovimientoExtracto', 'fechaValor', 'valueDate'),
      ('MovimientoExtracto', 'descripcion', 'description'),
      ('MovimientoExtracto', 'referenciaExterna', 'externalReference'),
      ('MovimientoExtracto', 'direccion', 'direction'),
      ('MovimientoExtracto', 'importe', 'amount'),
      ('MovimientoExtracto', 'estado', 'status'),
      ('MovimientoExtracto', 'pagoId', 'paymentId'),
      ('MovimientoExtracto', 'conciliadoPorId', 'reconciledById'),
      ('MovimientoExtracto', 'conciliadoAt', 'reconciledAt'),
      ('MovimientoExtracto', 'incidencia', 'issue'),
      ('ArqueoCaja', 'cuentaFondosId', 'fundsAccountId'),
      ('ArqueoCaja', 'fecha', 'date'),
      ('ArqueoCaja', 'custodioId', 'custodianId'),
      ('ArqueoCaja', 'verificadorId', 'verifierId'),
      ('ArqueoCaja', 'efectivoContado', 'countedCash'),
      ('ArqueoCaja', 'justificantes', 'receipts'),
      ('ArqueoCaja', 'fondoFijo', 'fixedFloat'),
      ('ArqueoCaja', 'diferencia', 'variance'),
      ('ArqueoCaja', 'estado', 'status'),
      ('ArqueoCaja', 'observaciones', 'notes'),
      ('ReposicionCaja', 'cuentaFondosId', 'fundsAccountId'),
      ('ReposicionCaja', 'arqueoId', 'cashCountId'),
      ('ReposicionCaja', 'importe', 'amount'),
      ('ReposicionCaja', 'importeJustificado', 'justifiedAmount'),
      ('ReposicionCaja', 'estado', 'status'),
      ('ReposicionCaja', 'creadaPorId', 'createdById'),
      ('ReposicionCaja', 'ejecutadaAt', 'executedAt'),
      ('CambioCuentaAcreedor', 'acreedorId', 'creditorId'),
      ('CambioCuentaAcreedor', 'cuentaAnterior4', 'previousAccountLast4'),
      ('CambioCuentaAcreedor', 'cuentaNueva4', 'newAccountLast4'),
      ('CambioCuentaAcreedor', 'motivo', 'reason'),
      ('CambioCuentaAcreedor', 'solicitadoPorId', 'requestedById'),
      ('CambioCuentaAcreedor', 'autorizadoPorId', 'authorizedById'),
      ('CambioCuentaAcreedor', 'estado', 'status'),
      ('CambioCuentaAcreedor', 'confirmacionCanal', 'confirmationChannel'),
      ('CambioCuentaAcreedor', 'autorizadoAt', 'authorizedAt'),
      ('AdjuntoPago', 'nombreArchivo', 'fileName'),
      ('AdjuntoPago', 'tamano', 'sizeBytes'),
      ('AdjuntoPago', 'facturaId', 'invoiceId'),
      ('AdjuntoPago', 'subidoPorId', 'uploadedById'),
      ('CierreMensual', 'entidad', 'entity'),
      ('CierreMensual', 'anio', 'year'),
      ('CierreMensual', 'mes', 'month'),
      ('CierreMensual', 'estado', 'status'),
      ('CierreMensual', 'cerradoPorId', 'closedById'),
      ('CierreMensual', 'cerradoAt', 'closedAt'),
      ('CierreMensual', 'observaciones', 'notes'),
      ('IndicadorCierre', 'cierreId', 'closeId'),
      ('IndicadorCierre', 'codigo', 'code'),
      ('IndicadorCierre', 'cantidad', 'quantity'),
      ('IndicadorCierre', 'importe', 'amount'),
      ('IndicadorCierre', 'porcentaje', 'percentage'),
      ('IndicadorCierre', 'detalle', 'detail'),
      ('EventoAuditoria', 'accion', 'action'),
      ('EventoAuditoria', 'tipoRegistro', 'recordType'),
      ('EventoAuditoria', 'registroId', 'recordId'),
      ('EventoAuditoria', 'entidad', 'entity'),
      ('EventoAuditoria', 'motivo', 'reason'),
      ('EventoAuditoria', 'antes', 'before'),
      ('EventoAuditoria', 'despues', 'after')
    ) AS names(table_name, old_name, new_name)
  LOOP
    EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', pair.table_name, pair.old_name, pair.new_name);
  END LOOP;
END $$;

DO $$
DECLARE
  pair record;
BEGIN
  FOR pair IN
    SELECT * FROM (VALUES
      ('CierreTurno', 'ShiftClose'),
      ('Catalogo', 'Catalog'),
      ('Proveedor', 'Supplier'),
      ('ProveedorProducto', 'SupplierProduct'),
      ('Recepcion', 'Receipt'),
      ('Factura', 'Invoice'),
      ('FacturaLinea', 'InvoiceLine'),
      ('FacturaImpuesto', 'InvoiceTax'),
      ('FacturaGestoria', 'AccountingInvoice'),
      ('RecepcionLinea', 'ReceiptLine'),
      ('InventarioFisico', 'PhysicalInventory'),
      ('InventarioFisicoLinea', 'PhysicalInventoryLine'),
      ('Producto', 'Product'),
      ('Acreedor', 'Creditor'),
      ('MedioPago', 'PaymentMethod'),
      ('CuentaFondos', 'FundsAccount'),
      ('CategoriaGasto', 'ExpenseCategory'),
      ('ParametroAutorizacion', 'AuthorizationParameter'),
      ('ReglaAutorizacion', 'AuthorizationRule'),
      ('AsignacionPagoUsuario', 'UserPaymentAssignment'),
      ('ContratoRecurrente', 'RecurringContract'),
      ('GastoCorriente', 'CurrentExpense'),
      ('Anticipo', 'Advance'),
      ('SecuenciaPago', 'PaymentSequence'),
      ('Pago', 'Payment'),
      ('PagoAplicacion', 'PaymentApplication'),
      ('AprobacionPago', 'PaymentApproval'),
      ('MovimientoFondos', 'FundsMovement'),
      ('ImportacionExtracto', 'StatementImport'),
      ('MovimientoExtracto', 'StatementMovement'),
      ('ArqueoCaja', 'CashCount'),
      ('ReposicionCaja', 'CashReplenishment'),
      ('CambioCuentaAcreedor', 'CreditorAccountChange'),
      ('AdjuntoPago', 'PaymentAttachment'),
      ('CierreMensual', 'MonthlyClose'),
      ('IndicadorCierre', 'CloseMetric'),
      ('EventoAuditoria', 'AuditEvent')
    ) AS names(old_name, new_name)
  LOOP
    EXECUTE format('ALTER TABLE %I RENAME TO %I', pair.old_name, pair.new_name);
  END LOOP;
END $$;

DO $$
DECLARE
  pair record;
  item record;
  renamed_name text;
BEGIN
  -- Rename constraint names after their tables and columns have moved.
  FOR item IN
    SELECT n.nspname AS schema_name, c.relname AS table_name, con.conname AS old_name
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname <> '_prisma_migrations'
  LOOP
    renamed_name := item.old_name;
    FOR pair IN
      SELECT * FROM (VALUES
        ('Acreedor', 'Creditor'), ('AdjuntoPago', 'PaymentAttachment'), ('Anticipo', 'Advance'),
        ('AprobacionPago', 'PaymentApproval'), ('ArqueoCaja', 'CashCount'),
        ('AsignacionPagoUsuario', 'UserPaymentAssignment'), ('CambioCuentaAcreedor', 'CreditorAccountChange'),
        ('Catalogo', 'Catalog'), ('CategoriaGasto', 'ExpenseCategory'), ('CierreMensual', 'MonthlyClose'),
        ('CierreTurno', 'ShiftClose'), ('ContratoRecurrente', 'RecurringContract'),
        ('CuentaFondos', 'FundsAccount'), ('EventoAuditoria', 'AuditEvent'), ('Factura', 'Invoice'),
        ('FacturaGestoria', 'AccountingInvoice'), ('FacturaImpuesto', 'InvoiceTax'),
        ('FacturaLinea', 'InvoiceLine'), ('GastoCorriente', 'CurrentExpense'),
        ('ImportacionExtracto', 'StatementImport'), ('IndicadorCierre', 'CloseMetric'),
        ('InventarioFisico', 'PhysicalInventory'), ('InventarioFisicoLinea', 'PhysicalInventoryLine'),
        ('MedioPago', 'PaymentMethod'), ('MovimientoExtracto', 'StatementMovement'),
        ('MovimientoFondos', 'FundsMovement'), ('Pago', 'Payment'), ('PagoAplicacion', 'PaymentApplication'),
        ('ParametroAutorizacion', 'AuthorizationParameter'), ('Producto', 'Product'),
        ('Proveedor', 'Supplier'), ('ProveedorProducto', 'SupplierProduct'), ('Recepcion', 'Receipt'),
        ('RecepcionLinea', 'ReceiptLine'), ('ReglaAutorizacion', 'AuthorizationRule'),
        ('ReposicionCaja', 'CashReplenishment'), ('SecuenciaPago', 'PaymentSequence')
      ) AS names(old_name, new_name)
    LOOP
      renamed_name := replace(renamed_name, pair.old_name || '_', pair.new_name || '_');
    END LOOP;

    FOR pair IN
      SELECT * FROM (VALUES
        ('turno', 'shift'), ('efectivo', 'cash'), ('caixa', 'caixaBankAmount'), ('santander', 'santanderAmount'),
        ('efectivoGasto', 'cashExpense'), ('fondoInicial', 'openingFund'), ('fondoFinal', 'closingFund'),
        ('numeroCierreCaja', 'cashCloseNumber'), ('fechaHoraApertura', 'openingDateTime'),
        ('fechaHoraCierre', 'closingDateTime'), ('fondoCajaAnterior', 'previousCashFund'),
        ('cobrosEfectivo', 'cashReceipts'), ('reembolsosEfectivo', 'cashRefunds'), ('depositado', 'depositedAmount'),
        ('pagosSalidas', 'paymentOutflows'), ('efectivoTeoricoCaja', 'theoreticalCash'),
        ('cantidadEfectivoReal', 'actualCash'), ('descuadre', 'cashVariance'), ('ventasBrutas', 'grossSales'),
        ('reembolsos', 'refunds'), ('descuentos', 'discounts'), ('ventasNetas', 'netSales'),
        ('ventasEfectivo', 'cashSales'), ('ventasTarjeta', 'cardSales'), ('ivaPan4Base', 'breadVat4Base'),
        ('ivaPan4Cuota', 'breadVat4Amount'), ('iva10Base', 'vat10Base'), ('iva10Cuota', 'vat10Amount'),
        ('observacionDescuadre', 'varianceNote'), ('confirmadoPorId', 'confirmedById'), ('confirmadoAt', 'confirmedAt'),
        ('proveedor', 'supplier'), ('importe', 'amount'), ('tipo', 'type'), ('valor', 'value'),
        ('descripcion', 'description'), ('prefijoCodigo', 'codePrefix'), ('activo', 'active'),
        ('razonSocial', 'legalName'), ('cifNif', 'taxId'), ('direccionFiscal', 'billingAddress'),
        ('contactoNombre', 'contactName'), ('contactoTelefono', 'contactPhone'), ('contactoEmail', 'contactEmail'),
        ('categoriaServicio', 'serviceCategory'), ('condicionesPago', 'paymentTerms'),
        ('plazoEntregaDias', 'deliveryLeadTimeDays'), ('pedidoMinimo', 'minimumOrder'),
        ('notasCondiciones', 'termsNotes'), ('frecuenciaEntrega', 'deliveryFrequency'),
        ('horarioEntrega', 'deliverySchedule'), ('metodoPedido', 'orderingMethod'), ('fechaAlta', 'addedAt'),
        ('estado', 'status'), ('valoracionFiabilidad', 'reliabilityRating'), ('valoracionCalidad', 'qualityRating'),
        ('valoracionPrecio', 'priceRating'), ('incidencias', 'issues'), ('observaciones', 'notes'),
        ('proveedorId', 'supplierId'), ('productoId', 'productId'), ('refProveedor', 'supplierReference'),
        ('precioCompraSinIva', 'purchasePriceExcludingVat'), ('esPrincipal', 'isPrimary'),
        ('codigoAlbaran', 'deliveryNoteCode'), ('facturaId', 'invoiceId'), ('fechaRecepcion', 'receivedAt'),
        ('serie', 'series'), ('numero', 'number'), ('fechaExpedicion', 'issueDate'), ('fechaOperacion', 'operationDate'),
        ('fechaVencimiento', 'dueDate'), ('fechaPago', 'paymentDate'), ('numeroPedido', 'orderNumber'),
        ('fechaPedido', 'orderDate'), ('centroEntrega', 'deliveryCenter'), ('referenciaAlbaran', 'deliveryNoteReference'),
        ('fechaAlbaran', 'deliveryNoteDate'), ('formaPago', 'paymentMethod'), ('estadoPago', 'paymentStatus'),
        ('moneda', 'currency'), ('importePagado', 'paidAmount'), ('entidad', 'entity'), ('tipoDocumento', 'documentType'),
        ('estadoCircuito', 'workflowStatus'), ('acreedorId', 'creditorId'), ('importeConformado', 'confirmedAmount'),
        ('importeRetenido', 'withheldAmount'), ('motivoRetencion', 'withholdingReason'),
        ('referenciaOrigen', 'sourceReference'), ('esLegacyPago', 'isLegacyPayment'),
        ('razonSocialEmisor', 'issuerLegalName'), ('nifEmisor', 'issuerTaxId'),
        ('domicilioFiscalEmisor', 'issuerBillingAddress'), ('totalNeto', 'netTotal'),
        ('totalDescuento', 'discountTotal'), ('totalIva', 'totalVat'), ('totalRecargo', 'surchargeTotal'),
        ('totalRetenciones', 'withholdingTotal'), ('importeTotal', 'totalAmount'), ('alertas', 'alerts'),
        ('tipoLinea', 'lineType'), ('referenciaProveedor', 'supplierReference'), ('codigoArticulo', 'itemCode'),
        ('unidadMedida', 'unitOfMeasure'), ('formatoOriginal', 'originalFormat'), ('cantidad', 'quantity'),
        ('descuentoPorcentaje', 'discountPercentage'), ('descuentoImporte', 'discountAmount'),
        ('precioUnitario', 'unitPrice'), ('precioUnitarioNeto', 'netUnitPrice'), ('baseImponible', 'taxableBase'),
        ('tipoIva', 'vatRate'), ('cuotaIva', 'vatAmount'), ('totalLinea', 'lineTotal'), ('lote', 'batch'),
        ('alertaValidacion', 'validationAlert'), ('porcentaje', 'percentage'), ('cuota', 'taxAmount'),
        ('fecha', 'date'), ('facturaNumero', 'invoiceNumber'), ('proveedorAcreedor', 'supplierOrCreditor'),
        ('nif', 'taxId'), ('concepto', 'concept'), ('baseExenta', 'exemptBase'), ('iva21', 'vat21'),
        ('iva10', 'vat10'), ('iva4', 'vat4'), ('iva2', 'vat2'), ('totalFactura', 'invoiceTotal'),
        ('textoOCR', 'ocrText'), ('origen', 'source'), ('creadoPorId', 'createdById'), ('creadoById', 'createdById'),
        ('recepcionId', 'receiptId'), ('cantidadRecibida', 'receivedQuantity'), ('fechaConteo', 'countedAt'),
        ('inventarioFisicoId', 'physicalInventoryId'), ('cantidadUm1', 'quantityUnit1'), ('cantidadUm2', 'quantityUnit2'),
        ('codigo', 'code'), ('codBarrasEan', 'eanBarcode'), ('descripcionTpv', 'posDescription'),
        ('descripcionCompleta', 'fullDescription'), ('tipoArticulo', 'itemType'), ('familia', 'family'),
        ('subfamilia', 'subfamily'), ('seccion', 'section'), ('esComprable', 'isPurchasable'),
        ('esElaborado', 'isPrepared'), ('esVendible', 'isSellable'), ('llevaReceta', 'hasRecipe'),
        ('umBaseStock', 'baseStockUnit'), ('umCompra', 'purchaseUnit'), ('factorCompraABase', 'purchaseToBaseFactor'),
        ('umVenta', 'salesUnit'), ('factorVentaABase', 'salesToBaseFactor'), ('pesoNetoUdG', 'netWeightPerUnitGrams'),
        ('formatoPresentacion', 'presentationFormat'), ('costeUmBase', 'baseUnitCost'), ('costeConIva', 'costIncludingVat'),
        ('mermaEstandarPct', 'standardWastePercentage'), ('codIva', 'vatCode'), ('ivaPct', 'vatPercentage'),
        ('ivaCompraPct', 'purchaseVatPercentage'), ('ivaVentaPct', 'salesVatPercentage'),
        ('metodoPrecio', 'pricingMethod'), ('margenObjetivoPct', 'targetMarginPercentage'),
        ('pvpObjetivoConIva', 'targetRetailPriceIncludingVat'), ('pvpFijoConIva', 'fixedRetailPriceIncludingVat'),
        ('pvpAplicadoConIva', 'appliedRetailPriceIncludingVat'), ('pvpAplicadoSinIva', 'appliedRetailPriceExcludingVat'),
        ('gananciaEurUd', 'profitPerUnit'), ('margenRealPct', 'actualMarginPercentage'),
        ('desviacionPp', 'percentagePointDeviation'), ('diferenciaEurUd', 'unitDifference'),
        ('diagnosticoPrecio', 'pricingDiagnosis'), ('controlaStock', 'stockControl'),
        ('metodoValoracion', 'valuationMethod'), ('stockMinimo', 'minimumStock'), ('stockMaximo', 'maximumStock'),
        ('puntoPedido', 'reorderPoint'), ('ubicacion', 'location'), ('claseAbc', 'abcClass'),
        ('controlLote', 'batchControl'), ('vidaUtilDias', 'shelfLifeDays'), ('conservacion', 'storageConditions'),
        ('alergenos', 'allergens'), ('esEjemplo', 'isExample'), ('nombre', 'name'),
        ('entidadHabitual', 'defaultEntity'), ('cuentaDestinoUltimos4', 'destinationAccountLast4'),
        ('requiereCuenta', 'requiresAccount'), ('conciliableBanco', 'bankReconciliable'), ('limiteOperacion', 'transactionLimit'),
        ('ibanUltimos4', 'ibanLast4'), ('responsableId', 'responsibleUserId'), ('saldoTeorico', 'theoreticalBalance'),
        ('fondoFijo', 'fixedFloat'), ('valorDecimal', 'decimalValue'), ('valorTexto', 'textValue'),
        ('vigenteDesde', 'validFrom'), ('vigenteHasta', 'validTo'), ('importeDesde', 'amountFrom'),
        ('importeHasta', 'amountTo'), ('funcionRequerida', 'requiredFunction'), ('funcion', 'function'),
        ('importeEsperado', 'expectedAmount'), ('tolerancia', 'tolerance'), ('periodicidad', 'frequency'),
        ('fechaInicio', 'startDate'), ('fechaFin', 'endDate'), ('contratoId', 'contractId'),
        ('fechaDevengo', 'accrualDate'), ('justificante', 'receipt'), ('solicitanteId', 'requesterId'),
        ('autorizadorId', 'authorizerId'), ('motivoRechazo', 'rejectionReason'), ('autorizadoAt', 'authorizedAt'),
        ('importeAplicado', 'appliedAmount'), ('solicitadoPorId', 'requestedById'), ('ultimoNumero', 'lastNumber'),
        ('medioPagoId', 'paymentMethodId'), ('cuentaFondosId', 'fundsAccountId'), ('referenciaExterna', 'externalReference'),
        ('ejecutadoPorId', 'executedById'), ('conciliado', 'reconciled'), ('excesoAutorizadoPorId', 'excessAuthorizedById'),
        ('motivoExceso', 'excessReason'), ('anuladoPorId', 'voidedById'), ('anuladoAt', 'voidedAt'),
        ('tipoDestino', 'destinationType'), ('gastoId', 'currentExpenseId'), ('anticipoId', 'advanceId'),
        ('usuarioId', 'userId'), ('motivo', 'reason'), ('origenTipo', 'sourceType'), ('origenId', 'sourceId'),
        ('nombreArchivo', 'fileName'), ('hashArchivo', 'fileHash'), ('fechaDesde', 'startDate'),
        ('fechaHasta', 'endDate'), ('importacionId', 'importId'), ('fechaValor', 'valueDate'),
        ('direccion', 'direction'), ('conciliadoPorId', 'reconciledById'), ('conciliadoAt', 'reconciledAt'),
        ('incidencia', 'issue'), ('custodioId', 'custodianId'), ('verificadorId', 'verifierId'),
        ('efectivoContado', 'countedCash'), ('justificantes', 'receipts'), ('diferencia', 'variance'),
        ('arqueoId', 'cashCountId'), ('importeJustificado', 'justifiedAmount'), ('ejecutadaAt', 'executedAt'),
        ('cuentaAnterior4', 'previousAccountLast4'), ('cuentaNueva4', 'newAccountLast4'),
        ('confirmacionCanal', 'confirmationChannel'), ('tamano', 'sizeBytes'), ('anio', 'year'), ('mes', 'month'),
        ('cerradoPorId', 'closedById'), ('cerradoAt', 'closedAt'), ('cierreId', 'closeId'), ('detalle', 'detail'),
        ('accion', 'action'), ('tipoRegistro', 'recordType'), ('registroId', 'recordId'), ('antes', 'before'), ('despues', 'after')
      ) AS fields(old_name, new_name)
    LOOP
      renamed_name := replace(renamed_name, '_' || pair.old_name || '_', '_' || pair.new_name || '_');
    END LOOP;

    IF renamed_name <> item.old_name THEN
      EXECUTE format('ALTER TABLE %I.%I RENAME CONSTRAINT %I TO %I', item.schema_name, item.table_name, item.old_name, renamed_name);
    END IF;
  END LOOP;

  -- Rename standalone indexes. Constraint-backed indexes follow constraint renames.
  FOR item IN
    SELECT schemaname AS schema_name, tablename AS table_name, indexname AS old_name
    FROM pg_indexes
    WHERE schemaname = 'public' AND tablename <> '_prisma_migrations'
  LOOP
    renamed_name := item.old_name;
    FOR pair IN
      SELECT * FROM (VALUES
        ('Acreedor', 'Creditor'), ('AdjuntoPago', 'PaymentAttachment'), ('Anticipo', 'Advance'),
        ('AprobacionPago', 'PaymentApproval'), ('ArqueoCaja', 'CashCount'), ('AsignacionPagoUsuario', 'UserPaymentAssignment'),
        ('CambioCuentaAcreedor', 'CreditorAccountChange'), ('Catalogo', 'Catalog'), ('CategoriaGasto', 'ExpenseCategory'),
        ('CierreMensual', 'MonthlyClose'), ('CierreTurno', 'ShiftClose'), ('ContratoRecurrente', 'RecurringContract'),
        ('CuentaFondos', 'FundsAccount'), ('EventoAuditoria', 'AuditEvent'), ('Factura', 'Invoice'),
        ('FacturaGestoria', 'AccountingInvoice'), ('FacturaImpuesto', 'InvoiceTax'), ('FacturaLinea', 'InvoiceLine'),
        ('GastoCorriente', 'CurrentExpense'), ('ImportacionExtracto', 'StatementImport'), ('IndicadorCierre', 'CloseMetric'),
        ('InventarioFisico', 'PhysicalInventory'), ('InventarioFisicoLinea', 'PhysicalInventoryLine'), ('MedioPago', 'PaymentMethod'),
        ('MovimientoExtracto', 'StatementMovement'), ('MovimientoFondos', 'FundsMovement'), ('Pago', 'Payment'),
        ('PagoAplicacion', 'PaymentApplication'), ('ParametroAutorizacion', 'AuthorizationParameter'), ('Producto', 'Product'),
        ('Proveedor', 'Supplier'), ('ProveedorProducto', 'SupplierProduct'), ('Recepcion', 'Receipt'),
        ('RecepcionLinea', 'ReceiptLine'), ('ReglaAutorizacion', 'AuthorizationRule'), ('ReposicionCaja', 'CashReplenishment'),
        ('SecuenciaPago', 'PaymentSequence')
      ) AS names(old_name, new_name)
    LOOP
      renamed_name := replace(renamed_name, pair.old_name || '_', pair.new_name || '_');
    END LOOP;

    FOR pair IN
      SELECT * FROM (VALUES
        ('turno', 'shift'), ('efectivo', 'cash'), ('caixa', 'caixaBankAmount'), ('santander', 'santanderAmount'),
        ('efectivoGasto', 'cashExpense'), ('fondoInicial', 'openingFund'), ('fondoFinal', 'closingFund'),
        ('numeroCierreCaja', 'cashCloseNumber'), ('confirmadoAt', 'confirmedAt'), ('proveedorId', 'supplierId'),
        ('productoId', 'productId'), ('facturaId', 'invoiceId'), ('fechaRecepcion', 'receivedAt'), ('estado', 'status'),
        ('tipo', 'type'), ('prefijoCodigo', 'codePrefix'), ('codigo', 'code'), ('fechaExpedicion', 'issueDate'),
        ('fechaAlbaran', 'deliveryNoteDate'), ('fechaPedido', 'orderDate'), ('fechaVencimiento', 'dueDate'),
        ('estadoPago', 'paymentStatus'), ('estadoCircuito', 'workflowStatus'), ('entidad', 'entity'),
        ('acreedorId', 'creditorId'), ('numero', 'number'), ('serie', 'series'), ('fecha', 'date'),
        ('cifNif', 'taxId'), ('familia', 'family'), ('seccion', 'section'), ('tipoArticulo', 'itemType'),
        ('cuentaFondosId', 'fundsAccountId'), ('fechaValor', 'valueDate'), ('pagoId', 'paymentId'),
        ('gastoId', 'currentExpenseId'), ('anticipoId', 'advanceId'), ('importeDesde', 'amountFrom'),
        ('importeHasta', 'amountTo'), ('fechaInicio', 'startDate'), ('funcion', 'function'), ('activo', 'active'),
        ('fechaDevengo', 'accrualDate'), ('importacionId', 'importId'), ('registroId', 'recordId'),
        ('tipoRegistro', 'recordType'), ('createdAt', 'createdAt'), ('shiftId', 'shiftId'), ('userId', 'userId')
      ) AS fields(old_name, new_name)
    LOOP
      renamed_name := replace(renamed_name, '_' || pair.old_name || '_', '_' || pair.new_name || '_');
    END LOOP;

    IF renamed_name <> item.old_name THEN
      EXECUTE format('ALTER INDEX %I.%I RENAME TO %I', item.schema_name, item.old_name, renamed_name);
    END IF;
  END LOOP;
END $$;
